### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by LL-MF** [rabbitmask/Libra#1]
1.请问下如何自定义或者修改规则库文件
2.站点js内的链接是否会爬取检测

**Comment by rabbitmask** [comment]
1、navicat打开根目录下的db文件，是个sqllite，里面可以调整规则库
2、file_type_black=['.css','.jpg','png','bmp','.gif','.zip','.rar'] 默认的黑名单没有js的，so，当前根目录的js是爬取的，但没有做多层爬取，主要考虑容易爬偏，有些外链涉及比较庞大，所以目前的设计思想是只爬取一层
