### ISSUE TITLE
No module named Config.config_banner

### ISSUE THREAD

**Issue by hanzhen668** [rabbitmask/Libra#5]
运行命令  
python2 Libra.py -u https://127.0.0.1
Traceback (most recent call last):
  File "Libra.py", line 11, in <module>
    from Config.config_banner import Libra_banner
ImportError: No module named Config.config_banner

刚下载完 pip安装了 requirements.txt
运行命令就报上面的错。

**Comment by rabbitmask** [comment]
大哥，py3的~ py2官方都停了两年了，默认py3
